import {
  createGeneratorFixture,
  createIterableFixture,
  createIteratorFixture,
  // @ts-ignore
} from '../fixture';
import { summary } from '../../src';

describe.each([
  ...dataProviderForArraysTrue(),
  ...dataProviderForGeneratorsTrue(),
  ...dataProviderForIterablesTrue(),
  ...dataProviderForIteratorsTrue(),
  ...dataProviderForStringsTrue(),
  ...dataProviderForSetsTrue(),
] as Array<[Iterable<unknown>|Iterator<unknown>]>)(
  "Summary Are Permutations Test True",
  (input: Iterable<unknown>|Iterator<unknown>) => {
    it("", () => {
      expect(summary.arePermutations(input)).toBeTruthy();
    });
  }
);

describe.each([
  ...dataProviderForArraysFalse(),
  // ...dataProviderForGeneratorsFalse(),
  // ...dataProviderForIterablesFalse(),
  // ...dataProviderForIteratorsFalse(),
  // ...dataProviderForStringsFalse(),
  // ...dataProviderForSetsFalse(),
] as Array<[Iterable<unknown>|Iterator<unknown>]>)(
  "Summary Are Permutations Test False",
  (input: Iterable<unknown>|Iterator<unknown>) => {
    it("", () => {
      expect(summary.arePermutations(input)).toBeFalsy();
    });
  }
);

function dataProviderForArraysTrue(): Array<unknown> {
  return [
    [],
    [[]],
    [[], []],
    [[], [], []],
    [[1]],
    [[1], [1]],
    [[1], [1], [1]],
    [[1, 1]],
    [[1, 1], [1, 1]],
    [[1, 1], [1, 1], [1, 1]],
    [[1, 2]],
    [[1, 2], [1, 2]],
    [[1, 2], [2, 1]],
    [[2, 1], [1, 2]],
    [[1, 2], [1, 2], [1, 2]],
    [[1, 2], [1, 2], [2, 1]],
    [[1, 2], [2, 1], [1, 2]],
    [[1, 2], [2, 1], [2, 1]],
    [[2, 1], [1, 2], [1, 2]],
    [[2, 1], [1, 2], [2, 1]],
    [[2, 1], [2, 1], [1, 2]],
    [[2, 1], [2, 1], [2, 1]],
    [[1, 1, 1]],
    [[1, 1, 1], [1, 1, 1]],
    [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
    [[1, 1, 2]],
    [[1, 1, 2], [1, 1, 2]],
    [[1, 1, 2], [1, 2, 1]],
    [[1, 1, 2], [2, 1, 1]],
    [[1, 1, 2], [1, 1, 2], [1, 1, 2]],
    [[1, 1, 2], [1, 1, 2], [1, 2, 1]],
    [[1, 1, 2], [1, 1, 2], [2, 1, 1]],
    [[1, 1, 2], [1, 2, 1], [1, 1, 2]],
    [[1, 1, 2], [1, 2, 1], [1, 2, 1]],
    [[1, 1, 2], [1, 2, 1], [2, 1, 1]],
    [[1, 1, 2], [2, 1, 1], [1, 1, 2]],
    [[1, 1, 2], [2, 1, 1], [1, 2, 1]],
    [[1, 1, 2], [2, 1, 1], [2, 1, 1]],
    [[1, 2, 1], [1, 1, 2], [1, 1, 2]],
    [[1, 2, 1], [1, 1, 2], [1, 2, 1]],
    [[1, 2, 1], [1, 1, 2], [2, 1, 1]],
    [[1, 2, 1], [1, 2, 1], [1, 1, 2]],
    [[1, 2, 1], [1, 2, 1], [1, 2, 1]],
    [[1, 2, 1], [1, 2, 1], [2, 1, 1]],
    [[1, 2, 1], [2, 1, 1], [1, 1, 2]],
    [[1, 2, 1], [2, 1, 1], [1, 2, 1]],
    [[1, 2, 1], [2, 1, 1], [2, 1, 1]],
    [[2, 1, 1], [1, 1, 2], [1, 1, 2]],
    [[2, 1, 1], [1, 1, 2], [1, 2, 1]],
    [[2, 1, 1], [1, 1, 2], [2, 1, 1]],
    [[2, 1, 1], [1, 2, 1], [1, 1, 2]],
    [[2, 1, 1], [1, 2, 1], [1, 2, 1]],
    [[2, 1, 1], [1, 2, 1], [2, 1, 1]],
    [[2, 1, 1], [2, 1, 1], [1, 1, 2]],
    [[2, 1, 1], [2, 1, 1], [1, 2, 1]],
    [[2, 1, 1], [2, 1, 1], [2, 1, 1]],
    [[1, 2, 3]],
    [[1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 3, 2]],
    [[1, 2, 3], [2, 1, 3]],
    [[1, 2, 3], [2, 3, 1]],
    [[1, 2, 3], [3, 1, 2]],
    [[1, 2, 3], [3, 2, 1]],
    [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 3, 2]],
    [[1, 2, 3], [1, 2, 3], [2, 1, 3]],
    [[1, 2, 3], [1, 2, 3], [2, 3, 1]],
    [[1, 2, 3], [1, 2, 3], [3, 1, 2]],
    [[1, 2, 3], [1, 2, 3], [3, 2, 1]],
    [[1, 2, 3], [1, 3, 2], [1, 2, 3]],
    [[1, 2, 3], [1, 3, 2], [1, 3, 2]],
    [[1, 2, 3], [1, 3, 2], [2, 1, 3]],
    [[1, 2, 3], [1, 3, 2], [2, 3, 1]],
    [[1, 2, 3], [1, 3, 2], [3, 1, 2]],
    [[1, 2, 3], [1, 3, 2], [3, 2, 1]],
    [[1, 2, 3], [2, 1, 3], [1, 2, 3]],
    [[1, 2, 3], [2, 1, 3], [1, 3, 2]],
    [[1, 2, 3], [2, 1, 3], [2, 1, 3]],
    [[1, 2, 3], [2, 1, 3], [2, 3, 1]],
    [[1, 2, 3], [2, 1, 3], [3, 1, 2]],
    [[1, 2, 3], [2, 1, 3], [3, 2, 1]],
    [[1, 2, 3], [2, 3, 1], [1, 2, 3]],
    [[1, 2, 3], [2, 3, 1], [1, 3, 2]],
    [[1, 2, 3], [2, 3, 1], [2, 1, 3]],
    [[1, 2, 3], [2, 3, 1], [2, 3, 1]],
    [[1, 2, 3], [2, 3, 1], [3, 1, 2]],
    [[1, 2, 3], [2, 3, 1], [3, 2, 1]],
    [[1, 2, 3], [3, 1, 2], [1, 2, 3]],
    [[1, 2, 3], [3, 1, 2], [1, 3, 2]],
    [[1, 2, 3], [3, 1, 2], [2, 1, 3]],
    [[1, 2, 3], [3, 1, 2], [2, 3, 1]],
    [[1, 2, 3], [3, 1, 2], [3, 1, 2]],
    [[1, 2, 3], [3, 1, 2], [3, 2, 1]],
    [[1, 2, 3], [3, 2, 1], [1, 2, 3]],
    [[1, 2, 3], [3, 2, 1], [1, 3, 2]],
    [[1, 2, 3], [3, 2, 1], [2, 1, 3]],
    [[1, 2, 3], [3, 2, 1], [2, 3, 1]],
    [[1, 2, 3], [3, 2, 1], [3, 1, 2]],
    [[1, 2, 3], [3, 2, 1], [3, 2, 1]],
    [['1', 2.2, 3], ['1', 2.2, 3]],
    [['1', 2.2, 3], ['1', 3, 2.2]],
    [['1', 2.2, 3], [2.2, '1', 3]],
    [['1', 2.2, 3], [2.2, 3, '1']],
    [['1', 2.2, 3], [3, '1', 2.2]],
    [['1', 2.2, 3], [3, 2.2, '1']],
    [[true, [2], null], [true, [2], null]],
    [[true, [2], null], [true, null, [2]]],
    [[true, [2], null], [[2], true, null]],
    [[true, [2], null], [[2], null, true]],
    [[true, [2], null], [null, true, [2]]],
    [[true, [2], null], [null, [2], true]],
    [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]],
    [[1, 2, 3, 4, 5], [2, 3, 4, 5, 1], [1, 2, 3, 4, 5], [2, 4, 1, 3, 5]],
    [['a', 'b', 'c'], ['a', 'c', 'b'], ['b', 'a', 'c'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'a']],
  ];
}

function dataProviderForGeneratorsTrue(): Array<unknown> {
  return [
    [],
    [createGeneratorFixture([])],
    [createGeneratorFixture([]), createGeneratorFixture([])],
    [createGeneratorFixture([]), createGeneratorFixture([]), createGeneratorFixture([])],
    [createGeneratorFixture([1])],
    [createGeneratorFixture([1]), createGeneratorFixture([1])],
    [createGeneratorFixture([1]), createGeneratorFixture([1]), createGeneratorFixture([1])],
    [createGeneratorFixture([1, 1])],
    [createGeneratorFixture([1, 1]), createGeneratorFixture([1, 1])],
    [createGeneratorFixture([1, 1]), createGeneratorFixture([1, 1]), createGeneratorFixture([1, 1])],
    [createGeneratorFixture([1, 2])],
    [createGeneratorFixture([1, 2]), createGeneratorFixture([1, 2])],
    [createGeneratorFixture([1, 2]), createGeneratorFixture([2, 1])],
    [createGeneratorFixture([2, 1]), createGeneratorFixture([1, 2])],
    [createGeneratorFixture([1, 2]), createGeneratorFixture([1, 2]), createGeneratorFixture([1, 2])],
    [createGeneratorFixture([1, 2]), createGeneratorFixture([1, 2]), createGeneratorFixture([2, 1])],
    [createGeneratorFixture([1, 2]), createGeneratorFixture([2, 1]), createGeneratorFixture([1, 2])],
    [createGeneratorFixture([1, 2]), createGeneratorFixture([2, 1]), createGeneratorFixture([2, 1])],
    [createGeneratorFixture([2, 1]), createGeneratorFixture([1, 2]), createGeneratorFixture([1, 2])],
    [createGeneratorFixture([2, 1]), createGeneratorFixture([1, 2]), createGeneratorFixture([2, 1])],
    [createGeneratorFixture([2, 1]), createGeneratorFixture([2, 1]), createGeneratorFixture([1, 2])],
    [createGeneratorFixture([2, 1]), createGeneratorFixture([2, 1]), createGeneratorFixture([2, 1])],
    [createGeneratorFixture([1, 1, 1])],
    [createGeneratorFixture([1, 1, 1]), createGeneratorFixture([1, 1, 1])],
    [createGeneratorFixture([1, 1, 1]), createGeneratorFixture([1, 1, 1]), createGeneratorFixture([1, 1, 1])],
    [createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([1, 2, 1]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture( [1, 2, 1])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 1, 2]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 2, 1]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 1, 2])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([1, 2, 1])],
    [createGeneratorFixture([2, 1, 1]), createGeneratorFixture([2, 1, 1]), createGeneratorFixture([2, 1, 1])],
    [createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2]), createGeneratorFixture([3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([1, 3, 2]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3]), createGeneratorFixture([3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 1, 3]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1]), createGeneratorFixture( [3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([2, 3, 1]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2]), createGeneratorFixture([3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 1, 2]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1]), createGeneratorFixture([1, 2, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1]), createGeneratorFixture([1, 3, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1]), createGeneratorFixture([2, 1, 3])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1]), createGeneratorFixture([2, 3, 1])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1]), createGeneratorFixture([3, 1, 2])],
    [createGeneratorFixture([1, 2, 3]), createGeneratorFixture([3, 2, 1]), createGeneratorFixture([3, 2, 1])],
    [createGeneratorFixture(['1', 2.2, 3]), createGeneratorFixture(['1', 2.2, 3])],
    [createGeneratorFixture(['1', 2.2, 3]), createGeneratorFixture(['1', 3, 2.2])],
    [createGeneratorFixture(['1', 2.2, 3]), createGeneratorFixture([2.2, '1', 3])],
    [createGeneratorFixture(['1', 2.2, 3]), createGeneratorFixture([2.2, 3, '1'])],
    [createGeneratorFixture(['1', 2.2, 3]), createGeneratorFixture([3, '1', 2.2])],
    [createGeneratorFixture(['1', 2.2, 3]), createGeneratorFixture([3, 2.2, '1'])],
    [createGeneratorFixture([true, [2], null]), createGeneratorFixture([true, [2], null])],
    [createGeneratorFixture([true, [2], null]), createGeneratorFixture([true, null, [2]])],
    [createGeneratorFixture([true, [2], null]), createGeneratorFixture([[2], true, null])],
    [createGeneratorFixture([true, [2], null]), createGeneratorFixture([[2], null, true])],
    [createGeneratorFixture([true, [2], null]), createGeneratorFixture([null, true, [2]])],
    [createGeneratorFixture([true, [2], null]), createGeneratorFixture([null, [2], true])],
    [createGeneratorFixture([1, 1, 1, 1, 1]), createGeneratorFixture([1, 1, 1, 1, 1]), createGeneratorFixture([1, 1, 1, 1, 1])],
    [createGeneratorFixture([1, 2, 3, 4, 5]), createGeneratorFixture([2, 3, 4, 5, 1]), createGeneratorFixture([1, 2, 3, 4, 5]), createGeneratorFixture([2, 4, 1, 3, 5])],
    [createGeneratorFixture(['a', 'b', 'c']), createGeneratorFixture(['a', 'c', 'b']), createGeneratorFixture(['b', 'a', 'c']), createGeneratorFixture(['b', 'c', 'a']), createGeneratorFixture(['c', 'a', 'b']), createGeneratorFixture(['c', 'b', 'a'])],
  ];
}

function dataProviderForIterablesTrue(): Array<unknown> {
  return [
    [],
    [createIterableFixture([])],
    [createIterableFixture([]), createIterableFixture([])],
    [createIterableFixture([]), createIterableFixture([]), createIterableFixture([])],
    [createIterableFixture([1])],
    [createIterableFixture([1]), createIterableFixture([1])],
    [createIterableFixture([1]), createIterableFixture([1]), createIterableFixture([1])],
    [createIterableFixture([1, 1])],
    [createIterableFixture([1, 1]), createIterableFixture([1, 1])],
    [createIterableFixture([1, 1]), createIterableFixture([1, 1]), createIterableFixture([1, 1])],
    [createIterableFixture([1, 2])],
    [createIterableFixture([1, 2]), createIterableFixture([1, 2])],
    [createIterableFixture([1, 2]), createIterableFixture([2, 1])],
    [createIterableFixture([2, 1]), createIterableFixture([1, 2])],
    [createIterableFixture([1, 2]), createIterableFixture([1, 2]), createIterableFixture([1, 2])],
    [createIterableFixture([1, 2]), createIterableFixture([1, 2]), createIterableFixture([2, 1])],
    [createIterableFixture([1, 2]), createIterableFixture([2, 1]), createIterableFixture([1, 2])],
    [createIterableFixture([1, 2]), createIterableFixture([2, 1]), createIterableFixture([2, 1])],
    [createIterableFixture([2, 1]), createIterableFixture([1, 2]), createIterableFixture([1, 2])],
    [createIterableFixture([2, 1]), createIterableFixture([1, 2]), createIterableFixture([2, 1])],
    [createIterableFixture([2, 1]), createIterableFixture([2, 1]), createIterableFixture([1, 2])],
    [createIterableFixture([2, 1]), createIterableFixture([2, 1]), createIterableFixture([2, 1])],
    [createIterableFixture([1, 1, 1])],
    [createIterableFixture([1, 1, 1]), createIterableFixture([1, 1, 1])],
    [createIterableFixture([1, 1, 1]), createIterableFixture([1, 1, 1]), createIterableFixture([1, 1, 1])],
    [createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 2, 1]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 2, 1]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([1, 2, 1]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([1, 1, 2]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([1, 2, 1]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([1, 2, 1]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([1, 2, 1]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([2, 1, 1]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([2, 1, 1]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([1, 2, 1]), createIterableFixture([2, 1, 1]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([1, 1, 2]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([1, 1, 2]), createIterableFixture( [1, 2, 1])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([1, 1, 2]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([1, 2, 1]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([1, 2, 1]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([1, 2, 1]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([2, 1, 1]), createIterableFixture([1, 1, 2])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([2, 1, 1]), createIterableFixture([1, 2, 1])],
    [createIterableFixture([2, 1, 1]), createIterableFixture([2, 1, 1]), createIterableFixture([2, 1, 1])],
    [createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2]), createIterableFixture([3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([1, 3, 2]), createIterableFixture([3, 2, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3]), createIterableFixture([3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 1, 3]), createIterableFixture([3, 2, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1]), createIterableFixture( [3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([2, 3, 1]), createIterableFixture([3, 2, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2]), createIterableFixture([3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 1, 2]), createIterableFixture([3, 2, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1]), createIterableFixture([1, 2, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1]), createIterableFixture([1, 3, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1]), createIterableFixture([2, 1, 3])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1]), createIterableFixture([2, 3, 1])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1]), createIterableFixture([3, 1, 2])],
    [createIterableFixture([1, 2, 3]), createIterableFixture([3, 2, 1]), createIterableFixture([3, 2, 1])],
    [createIterableFixture(['1', 2.2, 3]), createIterableFixture(['1', 2.2, 3])],
    [createIterableFixture(['1', 2.2, 3]), createIterableFixture(['1', 3, 2.2])],
    [createIterableFixture(['1', 2.2, 3]), createIterableFixture([2.2, '1', 3])],
    [createIterableFixture(['1', 2.2, 3]), createIterableFixture([2.2, 3, '1'])],
    [createIterableFixture(['1', 2.2, 3]), createIterableFixture([3, '1', 2.2])],
    [createIterableFixture(['1', 2.2, 3]), createIterableFixture([3, 2.2, '1'])],
    [createIterableFixture([true, [2], null]), createIterableFixture([true, [2], null])],
    [createIterableFixture([true, [2], null]), createIterableFixture([true, null, [2]])],
    [createIterableFixture([true, [2], null]), createIterableFixture([[2], true, null])],
    [createIterableFixture([true, [2], null]), createIterableFixture([[2], null, true])],
    [createIterableFixture([true, [2], null]), createIterableFixture([null, true, [2]])],
    [createIterableFixture([true, [2], null]), createIterableFixture([null, [2], true])],
    [createIterableFixture([1, 1, 1, 1, 1]), createIterableFixture([1, 1, 1, 1, 1]), createIterableFixture([1, 1, 1, 1, 1])],
    [createIterableFixture([1, 2, 3, 4, 5]), createIterableFixture([2, 3, 4, 5, 1]), createIterableFixture([1, 2, 3, 4, 5]), createIterableFixture([2, 4, 1, 3, 5])],
    [createIterableFixture(['a', 'b', 'c']), createIterableFixture(['a', 'c', 'b']), createIterableFixture(['b', 'a', 'c']), createIterableFixture(['b', 'c', 'a']), createIterableFixture(['c', 'a', 'b']), createIterableFixture(['c', 'b', 'a'])],
  ];
}

function dataProviderForIteratorsTrue(): Array<unknown> {
  return [
    [],
    [createIteratorFixture([])],
    [createIteratorFixture([]), createIteratorFixture([])],
    [createIteratorFixture([]), createIteratorFixture([]), createIteratorFixture([])],
    [createIteratorFixture([1])],
    [createIteratorFixture([1]), createIteratorFixture([1])],
    [createIteratorFixture([1]), createIteratorFixture([1]), createIteratorFixture([1])],
    [createIteratorFixture([1, 1])],
    [createIteratorFixture([1, 1]), createIteratorFixture([1, 1])],
    [createIteratorFixture([1, 1]), createIteratorFixture([1, 1]), createIteratorFixture([1, 1])],
    [createIteratorFixture([1, 2])],
    [createIteratorFixture([1, 2]), createIteratorFixture([1, 2])],
    [createIteratorFixture([1, 2]), createIteratorFixture([2, 1])],
    [createIteratorFixture([2, 1]), createIteratorFixture([1, 2])],
    [createIteratorFixture([1, 2]), createIteratorFixture([1, 2]), createIteratorFixture([1, 2])],
    [createIteratorFixture([1, 2]), createIteratorFixture([1, 2]), createIteratorFixture([2, 1])],
    [createIteratorFixture([1, 2]), createIteratorFixture([2, 1]), createIteratorFixture([1, 2])],
    [createIteratorFixture([1, 2]), createIteratorFixture([2, 1]), createIteratorFixture([2, 1])],
    [createIteratorFixture([2, 1]), createIteratorFixture([1, 2]), createIteratorFixture([1, 2])],
    [createIteratorFixture([2, 1]), createIteratorFixture([1, 2]), createIteratorFixture([2, 1])],
    [createIteratorFixture([2, 1]), createIteratorFixture([2, 1]), createIteratorFixture([1, 2])],
    [createIteratorFixture([2, 1]), createIteratorFixture([2, 1]), createIteratorFixture([2, 1])],
    [createIteratorFixture([1, 1, 1])],
    [createIteratorFixture([1, 1, 1]), createIteratorFixture([1, 1, 1])],
    [createIteratorFixture([1, 1, 1]), createIteratorFixture([1, 1, 1]), createIteratorFixture([1, 1, 1])],
    [createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 2, 1]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 2, 1]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([1, 2, 1]), createIteratorFixture([2, 1, 1]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 1, 2]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 1, 2]), createIteratorFixture( [1, 2, 1])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 1, 2]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 2, 1]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 2, 1]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 1, 2])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([2, 1, 1]), createIteratorFixture([1, 2, 1])],
    [createIteratorFixture([2, 1, 1]), createIteratorFixture([2, 1, 1]), createIteratorFixture([2, 1, 1])],
    [createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2]), createIteratorFixture([3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([1, 3, 2]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3]), createIteratorFixture([3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 1, 3]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1]), createIteratorFixture( [3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([2, 3, 1]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2]), createIteratorFixture([3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 1, 2]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1]), createIteratorFixture([1, 2, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1]), createIteratorFixture([1, 3, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1]), createIteratorFixture([2, 1, 3])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1]), createIteratorFixture([2, 3, 1])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1]), createIteratorFixture([3, 1, 2])],
    [createIteratorFixture([1, 2, 3]), createIteratorFixture([3, 2, 1]), createIteratorFixture([3, 2, 1])],
    [createIteratorFixture(['1', 2.2, 3]), createIteratorFixture(['1', 2.2, 3])],
    [createIteratorFixture(['1', 2.2, 3]), createIteratorFixture(['1', 3, 2.2])],
    [createIteratorFixture(['1', 2.2, 3]), createIteratorFixture([2.2, '1', 3])],
    [createIteratorFixture(['1', 2.2, 3]), createIteratorFixture([2.2, 3, '1'])],
    [createIteratorFixture(['1', 2.2, 3]), createIteratorFixture([3, '1', 2.2])],
    [createIteratorFixture(['1', 2.2, 3]), createIteratorFixture([3, 2.2, '1'])],
    [createIteratorFixture([true, [2], null]), createIteratorFixture([true, [2], null])],
    [createIteratorFixture([true, [2], null]), createIteratorFixture([true, null, [2]])],
    [createIteratorFixture([true, [2], null]), createIteratorFixture([[2], true, null])],
    [createIteratorFixture([true, [2], null]), createIteratorFixture([[2], null, true])],
    [createIteratorFixture([true, [2], null]), createIteratorFixture([null, true, [2]])],
    [createIteratorFixture([true, [2], null]), createIteratorFixture([null, [2], true])],
    [createIteratorFixture([1, 1, 1, 1, 1]), createIteratorFixture([1, 1, 1, 1, 1]), createIteratorFixture([1, 1, 1, 1, 1])],
    [createIteratorFixture([1, 2, 3, 4, 5]), createIteratorFixture([2, 3, 4, 5, 1]), createIteratorFixture([1, 2, 3, 4, 5]), createIteratorFixture([2, 4, 1, 3, 5])],
    [createIteratorFixture(['a', 'b', 'c']), createIteratorFixture(['a', 'c', 'b']), createIteratorFixture(['b', 'a', 'c']), createIteratorFixture(['b', 'c', 'a']), createIteratorFixture(['c', 'a', 'b']), createIteratorFixture(['c', 'b', 'a'])],
  ];
}

function dataProviderForStringsTrue(): Array<unknown> {
  return [
    '',
    '1',
    '1111',
  ];
}

function dataProviderForSetsTrue(): Array<unknown> {
  return [
    [],
    [new Set([])],
    [new Set([]), new Set([])],
    [new Set([]), new Set([]), new Set([])],
    [new Set([1])],
    [new Set([1]), new Set([1])],
    [new Set([1]), new Set([1]), new Set([1])],
    [new Set([1, 2])],
    [new Set([1, 2]), new Set([1, 2])],
    [new Set([1, 2]), new Set([2, 1])],
    [new Set([2, 1]), new Set([1, 2])],
    [new Set([1, 2]), new Set([1, 2]), new Set([1, 2])],
    [new Set([1, 2]), new Set([1, 2]), new Set([2, 1])],
    [new Set([1, 2]), new Set([2, 1]), new Set([1, 2])],
    [new Set([1, 2]), new Set([2, 1]), new Set([2, 1])],
    [new Set([2, 1]), new Set([1, 2]), new Set([1, 2])],
    [new Set([2, 1]), new Set([1, 2]), new Set([2, 1])],
    [new Set([2, 1]), new Set([2, 1]), new Set([1, 2])],
    [new Set([2, 1]), new Set([2, 1]), new Set([2, 1])],
    [new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([3, 1, 2])],
    [new Set([1, 2, 3]), new Set([3, 2, 1])],
    [new Set([1, 2, 3]), new Set([1, 2, 3]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([1, 2, 3]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([1, 2, 3]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([1, 2, 3]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([1, 2, 3]), new Set([3, 1, 2])],
    [new Set([1, 2, 3]), new Set([1, 2, 3]), new Set([3, 2, 1])],
    [new Set([1, 2, 3]), new Set([1, 3, 2]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([1, 3, 2]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([1, 3, 2]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([1, 3, 2]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([1, 3, 2]), new Set([3, 1, 2])],
    [new Set([1, 2, 3]), new Set([1, 3, 2]), new Set([3, 2, 1])],
    [new Set([1, 2, 3]), new Set([2, 1, 3]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([2, 1, 3]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([2, 1, 3]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([2, 1, 3]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([2, 1, 3]), new Set([3, 1, 2])],
    [new Set([1, 2, 3]), new Set([2, 1, 3]), new Set([3, 2, 1])],
    [new Set([1, 2, 3]), new Set([2, 3, 1]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([2, 3, 1]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([2, 3, 1]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([2, 3, 1]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([2, 3, 1]), new Set( [3, 1, 2])],
    [new Set([1, 2, 3]), new Set([2, 3, 1]), new Set([3, 2, 1])],
    [new Set([1, 2, 3]), new Set([3, 1, 2]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([3, 1, 2]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([3, 1, 2]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([3, 1, 2]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([3, 1, 2]), new Set([3, 1, 2])],
    [new Set([1, 2, 3]), new Set([3, 1, 2]), new Set([3, 2, 1])],
    [new Set([1, 2, 3]), new Set([3, 2, 1]), new Set([1, 2, 3])],
    [new Set([1, 2, 3]), new Set([3, 2, 1]), new Set([1, 3, 2])],
    [new Set([1, 2, 3]), new Set([3, 2, 1]), new Set([2, 1, 3])],
    [new Set([1, 2, 3]), new Set([3, 2, 1]), new Set([2, 3, 1])],
    [new Set([1, 2, 3]), new Set([3, 2, 1]), new Set([3, 1, 2])],
    [new Set([1, 2, 3]), new Set([3, 2, 1]), new Set([3, 2, 1])],
    [new Set(['1', 2.2, 3]), new Set(['1', 2.2, 3])],
    [new Set(['1', 2.2, 3]), new Set(['1', 3, 2.2])],
    [new Set(['1', 2.2, 3]), new Set([2.2, '1', 3])],
    [new Set(['1', 2.2, 3]), new Set([2.2, 3, '1'])],
    [new Set(['1', 2.2, 3]), new Set([3, '1', 2.2])],
    [new Set(['1', 2.2, 3]), new Set([3, 2.2, '1'])],
    [new Set([true, [2], null]), new Set([true, [2], null])],
    [new Set([true, [2], null]), new Set([true, null, [2]])],
    [new Set([true, [2], null]), new Set([[2], true, null])],
    [new Set([true, [2], null]), new Set([[2], null, true])],
    [new Set([true, [2], null]), new Set([null, true, [2]])],
    [new Set([true, [2], null]), new Set([null, [2], true])],
    [new Set([1, 2, 3, 4, 5]), new Set([2, 3, 4, 5, 1]), new Set([1, 2, 3, 4, 5]), new Set([2, 4, 1, 3, 5])],
    [new Set(['a', 'b', 'c']), new Set(['a', 'c', 'b']), new Set(['b', 'a', 'c']), new Set(['b', 'c', 'a']), new Set(['c', 'a', 'b']), new Set(['c', 'b', 'a'])],
  ];
}

function dataProviderForArraysFalse(): Array<unknown> {
  return [
    [[1], []],
    [[], [1]],
    [[], [1], []],
    [[1, 2], [1, 2, 1]],
    [[1, 2, 2], [1, 2, 1]],
    [[1, 2, 1], [1, 2, 2]],
    [[1, 2, 1], [1, 2, '1']],
    [[1, 2, 1, 2, 1], [1, 2, 1, 2, 2]],
    [[1, 2, 1, 2, 1], [1, 2, 1, 2, '1']],
    [[1, 2, 3], [1, 2, 3], [2, 2, 3]],
    [[1, 2, 3], [2, 2, 3], [2, 2, 3]],
    [[2, 2, 3], [1, 2, 3], [2, 2, 3]],
    [[2, 2, 3], [1, 3, 2], [2, 2, 3]],
    [[2, 2, 3], [2, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 2, '3']],
    [['1', 2, 3], [1, '2', 3], [1, 2, '3']],
    [[1, 2, 3], [1, 2, 3], [2, 3, 4]],
    [[1, 2, 3], [2, 1, 3], [2, 3, 4]],
    [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    [[1.1, '2', [3], null], [1.1, '2', [3], null], [1.1, '2', [], null]],
    [[1.1, '2', [3], null], [1.1, '2', [], null], [1.1, '2', [], null]],
    [[1.1, '2', [3], null], [1.1, '2', [3], null], [1.1, '1', [3], null]],
    [[1.0, '2', [3], null], [1.1, '2', [3], null], [1.1, '2', [3], null]],
    [[1.0, '2', [3], null], [1.1, '2.0', [3], null], [1.1, '1', [], null]],
    [[1.0, '2', [3], null], [1.1, '2.0', [3], null], [1.1, '1', [], false]],
    [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1]],
    [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]],
    [['a', 'b', 'c'], ['a', 'c', 'b'], ['b', 'a', 'c'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'c']],
    [['a', 'b', 'c'], ['a', 'c', 'b'], ['b', 'b', 'c'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'a']],
    [['a', 'b', 'c'], ['a', 'c', 'c'], ['b', 'a', 'c'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'a']],
    [['a', 'b', 'c'], ['a', 'c', 'b'], ['b', 'a'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'a']],
    [['a', 'b', 'c'], ['c', 'b'], ['b', 'a', 'c'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'a']],
  ];
}

