// @ts-ignore
import { createGeneratorFixture, createIterableFixture, createIteratorFixture, createMapFixture } from "../fixture";
import { InvalidArgumentError, single } from "../../src";

describe.each([
  ...dataProviderForArrays(),
  ...dataProviderForGenerators(),
  ...dataProviderForIterables(),
  ...dataProviderForIterators(),
  ...dataProviderForStrings(),
  ...dataProviderForSets(),
  ...dataProviderForMaps(),
] as Array<[Iterable<unknown>|Iterator<unknown>, number, number, boolean, Array<unknown>]>)(
  "Chunkwise Overlap Test",
  (
    data: Iterable<unknown>|Iterator<unknown>,
    chunkSize: number,
    overlapSize: number,
    includeIncompleteTail: boolean,
    expected: Array<unknown>
  ) => {
    it("", () => {
      // Given
      const result = [];
      const chunks = single.chunkwiseOverlap(
        data,
        chunkSize,
        overlapSize,
        includeIncompleteTail,
      );

      // When
      for (const item of chunks) {
        result.push(item);
      }

      // Then
      expect(result).toEqual(expected);
    });
  }
);

describe.each([
  ...dataProviderForError(),
] as Array<[Iterable<unknown>|Iterator<unknown>, number, number, boolean]>)(
  "Chunkwise Overlap Error Test",
  (
    data: Iterable<unknown>|Iterator<unknown>,
    chunkSize: number,
    overlapSize: number,
    includeIncompleteTail: boolean
  ) => {
    it("", () => {
      expect(() => {
        const chunks = single.chunkwiseOverlap(
          data,
          chunkSize,
          overlapSize,
          includeIncompleteTail,
        );

        for (const _ of chunks) {
          break;
        }
      }).toThrow(InvalidArgumentError);
    });
  }
);

test("Chunkwise Overlap Default Param Value Test", () => {
  // Given
  const chunks = single.chunkwiseOverlap(
    [1, 2, 3, 4, 5],
    2,
    0,
  );
  const result = [];

  // When
  for (const item of chunks) {
    result.push(item);
  }

  // Then
  expect(result).toEqual([[1, 2], [3, 4], [5]]);
});

function dataProviderForArrays(): Array<unknown> {
  return [
    [
      [],
      1,
      0,
      true,
      [],
    ],
    [
      [],
      1,
      0,
      false,
      [],
    ],
    [
      [],
      2,
      0,
      true,
      [],
    ],
    [
      [],
      2,
      0,
      false,
      [],
    ],
    [
      [],
      2,
      1,
      true,
      [],
    ],
    [
      [],
      2,
      1,
      false,
      [],
    ],
    [
      [1],
      1,
      0,
      true,
      [[1]],
    ],
    [
      [1],
      1,
      0,
      false,
      [[1]],
    ],
    [
      [1],
      1,
      0,
      true,
      [[1]],
    ],
    [
      [1],
      1,
      0,
      false,
      [[1]],
    ],
    [
      [1],
      2,
      0,
      true,
      [[1]],
    ],
    [
      [1],
      2,
      0,
      false,
      [],
    ],
    [
      [1],
      2,
      1,
      true,
      [[1]],
    ],
    [
      [1],
      2,
      1,
      false,
      [],
    ],
    [
      [1],
      3,
      0,
      true,
      [[1]],
    ],
    [
      [1],
      3,
      0,
      false,
      [],
    ],
    [
      [1],
      3,
      1,
      true,
      [[1]],
    ],
    [
      [1],
      3,
      1,
      false,
      [],
    ],
    [
      [1],
      3,
      2,
      true,
      [[1]],
    ],
    [
      [1],
      3,
      2,
      false,
      [],
    ],
    [
      [1, 2],
      1,
      0,
      true,
      [[1], [2]],
    ],
    [
      [1, 2],
      1,
      0,
      false,
      [[1], [2]],
    ],
    [
      [1, 2],
      2,
      0,
      true,
      [[1, 2]],
    ],
    [
      [1, 2],
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      [1, 2],
      2,
      1,
      true,
      [[1, 2]],
    ],
    [
      [1, 2],
      2,
      1,
      false,
      [[1, 2]],
    ],
    [
      [1, 2],
      3,
      0,
      true,
      [[1, 2]],
    ],
    [
      [1, 2],
      3,
      0,
      false,
      [],
    ],
    [
      [1, 2],
      3,
      1,
      true,
      [[1, 2]],
    ],
    [
      [1, 2],
      3,
      1,
      false,
      [],
    ],
    [
      [1, 2],
      3,
      2,
      true,
      [[1, 2]],
    ],
    [
      [1, 2],
      3,
      2,
      false,
      [],
    ],
    [
      [1, 2, 3],
      1,
      0,
      true,
      [[1], [2], [3]],
    ],
    [
      [1, 2, 3],
      1,
      0,
      false,
      [[1], [2], [3]],
    ],
    [
      [1, 2, 3],
      2,
      0,
      true,
      [[1, 2], [3]],
    ],
    [
      [1, 2, 3],
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      [1, 2, 3],
      2,
      1,
      true,
      [[1, 2], [2, 3]],
    ],
    [
      [1, 2, 3],
      2,
      1,
      false,
      [[1, 2], [2, 3]],
    ],
    [
      [1, 2, 3],
      3,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      3,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      3,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      3,
      2,
      false,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      4,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      4,
      0,
      false,
      [],
    ],
    [
      [1, 2, 3],
      4,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      4,
      1,
      false,
      [],
    ],
    [
      [1, 2, 3],
      4,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      4,
      2,
      false,
      [],
    ],
    [
      [1, 2, 3],
      4,
      3,
      true,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3],
      4,
      3,
      false,
      [],
    ],
    [
      [1, 2, 3, 4],
      2,
      0,
      true,
      [[1, 2], [3, 4]],
    ],
    [
      [1, 2, 3, 4],
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      [1, 2, 3, 4],
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      [1, 2, 3, 4],
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      [1, 2, 3, 4],
      3,
      0,
      true,
      [[1, 2, 3], [4]],
    ],
    [
      [1, 2, 3, 4],
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3, 4],
      3,
      1,
      true,
      [[1, 2, 3], [3, 4]],
    ],
    [
      [1, 2, 3, 4],
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3, 4],
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      [1, 2, 3, 4],
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      [1, 2, 3, 4, 5],
      2,
      0,
      true,
      [[1, 2], [3, 4], [5]],
    ],
    [
      [1, 2, 3, 4, 5],
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      [1, 2, 3, 4, 5],
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      [1, 2, 3, 4, 5],
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      [1, 2, 3, 4, 5],
      3,
      0,
      true,
      [[1, 2, 3], [4, 5]],
    ],
    [
      [1, 2, 3, 4, 5],
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      [1, 2, 3, 4, 5],
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      [1, 2, 3, 4, 5],
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      [1, 2, 3, 4, 5],
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      [1, 2, 3, 4, 5],
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      [1.1, 2.2, 3.3, 4.4, 5.5],
      2,
      0,
      true,
      [[1.1, 2.2], [3.3, 4.4], [5.5]],
    ],
    [
      [1.1, 2.2, 3.3, 4.4, 5.5],
      2,
      0,
      false,
      [[1.1, 2.2], [3.3, 4.4]],
    ],
    [
      [1.1, 2.2, 3.3, 4.4, 5.5],
      2,
      1,
      true,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      [1.1, 2.2, 3.3, 4.4, 5.5],
      2,
      1,
      false,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      ['1', '2', '3', '4', '5'],
      2,
      0,
      true,
      [['1', '2'], ['3', '4'], ['5']],
    ],
    [
      ['1', '2', '3', '4', '5'],
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      ['1', '2', '3', '4', '5'],
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      ['1', '2', '3', '4', '5'],
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      [[1], [2], [3], [4], [5]],
      2,
      0,
      true,
      [[[1], [2]], [[3], [4]], [[5]]],
    ],
    [
      [[1], [2], [3], [4], [5]],
      2,
      0,
      false,
      [[[1], [2]], [[3], [4]]],
    ],
    [
      [[1], [2], [3], [4], [5]],
      2,
      1,
      true,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      [[1], [2], [3], [4], [5]],
      2,
      1,
      false,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      [true, true, false, false],
      2,
      0,
      true,
      [[true, true], [false, false]],
    ],
    [
      [true, true, false, false],
      2,
      0,
      false,
      [[true, true], [false, false]],
    ],
    [
      [true, true, false, false],
      2,
      1,
      true,
      [[true, true], [true, false], [false, false]],
    ],
    [
      [true, true, false, false],
      2,
      1,
      false,
      [[true, true], [true, false], [false, false]],
    ],
    [
      [1, 2.2, '3', [4], true, null, 'test data'],
      3,
      0,
      true,
      [[1, 2.2, '3'], [[4], true, null], ['test data']],
    ],
    [
      [1, 2.2, '3', [4], true, null, 'test data'],
      3,
      0,
      false,
      [[1, 2.2, '3'], [[4], true, null]],
    ],
    [
      [1, 2.2, '3', [4], true, null, 'test data'],
      3,
      1,
      true,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      [1, 2.2, '3', [4], true, null, 'test data'],
      3,
      1,
      false,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      [1, 2.2, '3', [4], true, null, 'test data'],
      3,
      2,
      true,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      [1, 2.2, '3', [4], true, null, 'test data'],
      3,
      2,
      false,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      ['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe'],
      2,
      0,
      true,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      ['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe'],
      2,
      0,
      false,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      ['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe'],
      2,
      1,
      true,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      ['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe'],
      2,
      1,
      false,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9], [9, 10]],
    ],
    [
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
    ],
  ];
}

function dataProviderForGenerators(): Array<unknown> {
  return [
    [
      createGeneratorFixture([]),
      1,
      0,
      true,
      [],
    ],
    [
      createGeneratorFixture([]),
      1,
      0,
      false,
      [],
    ],
    [
      createGeneratorFixture([]),
      2,
      0,
      true,
      [],
    ],
    [
      createGeneratorFixture([]),
      2,
      0,
      false,
      [],
    ],
    [
      createGeneratorFixture([]),
      2,
      1,
      true,
      [],
    ],
    [
      createGeneratorFixture([]),
      2,
      1,
      false,
      [],
    ],
    [
      createGeneratorFixture([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      2,
      0,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      2,
      0,
      false,
      [],
    ],
    [
      createGeneratorFixture([1]),
      2,
      1,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      2,
      1,
      false,
      [],
    ],
    [
      createGeneratorFixture([1]),
      3,
      0,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      3,
      0,
      false,
      [],
    ],
    [
      createGeneratorFixture([1]),
      3,
      1,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      3,
      1,
      false,
      [],
    ],
    [
      createGeneratorFixture([1]),
      3,
      2,
      true,
      [[1]],
    ],
    [
      createGeneratorFixture([1]),
      3,
      2,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2]),
      1,
      0,
      true,
      [[1], [2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      1,
      0,
      false,
      [[1], [2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      2,
      0,
      true,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      2,
      1,
      true,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      2,
      1,
      false,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      3,
      0,
      true,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      3,
      0,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2]),
      3,
      1,
      true,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      3,
      1,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2]),
      3,
      2,
      true,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2]),
      3,
      2,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      1,
      0,
      true,
      [[1], [2], [3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      1,
      0,
      false,
      [[1], [2], [3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      2,
      0,
      true,
      [[1, 2], [3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      2,
      1,
      true,
      [[1, 2], [2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      2,
      1,
      false,
      [[1, 2], [2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      3,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      3,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      3,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      3,
      2,
      false,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      0,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      1,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      2,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      3,
      true,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3]),
      4,
      3,
      false,
      [],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      2,
      0,
      true,
      [[1, 2], [3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      3,
      0,
      true,
      [[1, 2, 3], [4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      2,
      0,
      true,
      [[1, 2], [3, 4], [5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      3,
      0,
      true,
      [[1, 2, 3], [4, 5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      createGeneratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      true,
      [[1.1, 2.2], [3.3, 4.4], [5.5]],
    ],
    [
      createGeneratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      false,
      [[1.1, 2.2], [3.3, 4.4]],
    ],
    [
      createGeneratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      true,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      createGeneratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      false,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      createGeneratorFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      true,
      [['1', '2'], ['3', '4'], ['5']],
    ],
    [
      createGeneratorFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      createGeneratorFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      createGeneratorFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      createGeneratorFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      true,
      [[[1], [2]], [[3], [4]], [[5]]],
    ],
    [
      createGeneratorFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      false,
      [[[1], [2]], [[3], [4]]],
    ],
    [
      createGeneratorFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      true,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      createGeneratorFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      false,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      createGeneratorFixture([true, true, false, false]),
      2,
      0,
      true,
      [[true, true], [false, false]],
    ],
    [
      createGeneratorFixture([true, true, false, false]),
      2,
      0,
      false,
      [[true, true], [false, false]],
    ],
    [
      createGeneratorFixture([true, true, false, false]),
      2,
      1,
      true,
      [[true, true], [true, false], [false, false]],
    ],
    [
      createGeneratorFixture([true, true, false, false]),
      2,
      1,
      false,
      [[true, true], [true, false], [false, false]],
    ],
    [
      createGeneratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      true,
      [[1, 2.2, '3'], [[4], true, null], ['test data']],
    ],
    [
      createGeneratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      false,
      [[1, 2.2, '3'], [[4], true, null]],
    ],
    [
      createGeneratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      true,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      createGeneratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      false,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      createGeneratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      true,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      createGeneratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      false,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      createGeneratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      true,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      createGeneratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      false,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      createGeneratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      true,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      createGeneratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      false,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9], [9, 10]],
    ],
    [
      createGeneratorFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
    ],
  ];
}

function dataProviderForIterables(): Array<unknown> {
  return [
    [
      createIterableFixture([]),
      1,
      0,
      true,
      [],
    ],
    [
      createIterableFixture([]),
      1,
      0,
      false,
      [],
    ],
    [
      createIterableFixture([]),
      2,
      0,
      true,
      [],
    ],
    [
      createIterableFixture([]),
      2,
      0,
      false,
      [],
    ],
    [
      createIterableFixture([]),
      2,
      1,
      true,
      [],
    ],
    [
      createIterableFixture([]),
      2,
      1,
      false,
      [],
    ],
    [
      createIterableFixture([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      2,
      0,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      2,
      0,
      false,
      [],
    ],
    [
      createIterableFixture([1]),
      2,
      1,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      2,
      1,
      false,
      [],
    ],
    [
      createIterableFixture([1]),
      3,
      0,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      3,
      0,
      false,
      [],
    ],
    [
      createIterableFixture([1]),
      3,
      1,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      3,
      1,
      false,
      [],
    ],
    [
      createIterableFixture([1]),
      3,
      2,
      true,
      [[1]],
    ],
    [
      createIterableFixture([1]),
      3,
      2,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2]),
      1,
      0,
      true,
      [[1], [2]],
    ],
    [
      createIterableFixture([1, 2]),
      1,
      0,
      false,
      [[1], [2]],
    ],
    [
      createIterableFixture([1, 2]),
      2,
      0,
      true,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      2,
      1,
      true,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      2,
      1,
      false,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      3,
      0,
      true,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      3,
      0,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2]),
      3,
      1,
      true,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      3,
      1,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2]),
      3,
      2,
      true,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2]),
      3,
      2,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2, 3]),
      1,
      0,
      true,
      [[1], [2], [3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      1,
      0,
      false,
      [[1], [2], [3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      2,
      0,
      true,
      [[1, 2], [3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      2,
      1,
      true,
      [[1, 2], [2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      2,
      1,
      false,
      [[1, 2], [2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      3,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      3,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      3,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      3,
      2,
      false,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      0,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      1,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      2,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      3,
      true,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3]),
      4,
      3,
      false,
      [],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      2,
      0,
      true,
      [[1, 2], [3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      3,
      0,
      true,
      [[1, 2, 3], [4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      2,
      0,
      true,
      [[1, 2], [3, 4], [5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      3,
      0,
      true,
      [[1, 2, 3], [4, 5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      createIterableFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      true,
      [[1.1, 2.2], [3.3, 4.4], [5.5]],
    ],
    [
      createIterableFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      false,
      [[1.1, 2.2], [3.3, 4.4]],
    ],
    [
      createIterableFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      true,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      createIterableFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      false,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      createIterableFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      true,
      [['1', '2'], ['3', '4'], ['5']],
    ],
    [
      createIterableFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      createIterableFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      createIterableFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      createIterableFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      true,
      [[[1], [2]], [[3], [4]], [[5]]],
    ],
    [
      createIterableFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      false,
      [[[1], [2]], [[3], [4]]],
    ],
    [
      createIterableFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      true,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      createIterableFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      false,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      createIterableFixture([true, true, false, false]),
      2,
      0,
      true,
      [[true, true], [false, false]],
    ],
    [
      createIterableFixture([true, true, false, false]),
      2,
      0,
      false,
      [[true, true], [false, false]],
    ],
    [
      createIterableFixture([true, true, false, false]),
      2,
      1,
      true,
      [[true, true], [true, false], [false, false]],
    ],
    [
      createIterableFixture([true, true, false, false]),
      2,
      1,
      false,
      [[true, true], [true, false], [false, false]],
    ],
    [
      createIterableFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      true,
      [[1, 2.2, '3'], [[4], true, null], ['test data']],
    ],
    [
      createIterableFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      false,
      [[1, 2.2, '3'], [[4], true, null]],
    ],
    [
      createIterableFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      true,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      createIterableFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      false,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      createIterableFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      true,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      createIterableFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      false,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      createIterableFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      true,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      createIterableFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      false,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      createIterableFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      true,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      createIterableFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      false,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9], [9, 10]],
    ],
    [
      createIterableFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
    ],
  ];
}

function dataProviderForIterators(): Array<unknown> {
  return [
    [
      createIteratorFixture([]),
      1,
      0,
      true,
      [],
    ],
    [
      createIteratorFixture([]),
      1,
      0,
      false,
      [],
    ],
    [
      createIteratorFixture([]),
      2,
      0,
      true,
      [],
    ],
    [
      createIteratorFixture([]),
      2,
      0,
      false,
      [],
    ],
    [
      createIteratorFixture([]),
      2,
      1,
      true,
      [],
    ],
    [
      createIteratorFixture([]),
      2,
      1,
      false,
      [],
    ],
    [
      createIteratorFixture([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      2,
      0,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      2,
      0,
      false,
      [],
    ],
    [
      createIteratorFixture([1]),
      2,
      1,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      2,
      1,
      false,
      [],
    ],
    [
      createIteratorFixture([1]),
      3,
      0,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      3,
      0,
      false,
      [],
    ],
    [
      createIteratorFixture([1]),
      3,
      1,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      3,
      1,
      false,
      [],
    ],
    [
      createIteratorFixture([1]),
      3,
      2,
      true,
      [[1]],
    ],
    [
      createIteratorFixture([1]),
      3,
      2,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2]),
      1,
      0,
      true,
      [[1], [2]],
    ],
    [
      createIteratorFixture([1, 2]),
      1,
      0,
      false,
      [[1], [2]],
    ],
    [
      createIteratorFixture([1, 2]),
      2,
      0,
      true,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      2,
      1,
      true,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      2,
      1,
      false,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      3,
      0,
      true,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      3,
      0,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2]),
      3,
      1,
      true,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      3,
      1,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2]),
      3,
      2,
      true,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2]),
      3,
      2,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      1,
      0,
      true,
      [[1], [2], [3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      1,
      0,
      false,
      [[1], [2], [3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      2,
      0,
      true,
      [[1, 2], [3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      2,
      1,
      true,
      [[1, 2], [2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      2,
      1,
      false,
      [[1, 2], [2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      3,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      3,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      3,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      3,
      2,
      false,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      0,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      1,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      2,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      3,
      true,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3]),
      4,
      3,
      false,
      [],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      2,
      0,
      true,
      [[1, 2], [3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      3,
      0,
      true,
      [[1, 2, 3], [4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      2,
      0,
      true,
      [[1, 2], [3, 4], [5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      3,
      0,
      true,
      [[1, 2, 3], [4, 5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      createIteratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      true,
      [[1.1, 2.2], [3.3, 4.4], [5.5]],
    ],
    [
      createIteratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      false,
      [[1.1, 2.2], [3.3, 4.4]],
    ],
    [
      createIteratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      true,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      createIteratorFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      false,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      createIteratorFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      true,
      [['1', '2'], ['3', '4'], ['5']],
    ],
    [
      createIteratorFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      createIteratorFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      createIteratorFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      createIteratorFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      true,
      [[[1], [2]], [[3], [4]], [[5]]],
    ],
    [
      createIteratorFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      false,
      [[[1], [2]], [[3], [4]]],
    ],
    [
      createIteratorFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      true,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      createIteratorFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      false,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      createIteratorFixture([true, true, false, false]),
      2,
      0,
      true,
      [[true, true], [false, false]],
    ],
    [
      createIteratorFixture([true, true, false, false]),
      2,
      0,
      false,
      [[true, true], [false, false]],
    ],
    [
      createIteratorFixture([true, true, false, false]),
      2,
      1,
      true,
      [[true, true], [true, false], [false, false]],
    ],
    [
      createIteratorFixture([true, true, false, false]),
      2,
      1,
      false,
      [[true, true], [true, false], [false, false]],
    ],
    [
      createIteratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      true,
      [[1, 2.2, '3'], [[4], true, null], ['test data']],
    ],
    [
      createIteratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      false,
      [[1, 2.2, '3'], [[4], true, null]],
    ],
    [
      createIteratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      true,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      createIteratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      false,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      createIteratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      true,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      createIteratorFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      false,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      createIteratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      true,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      createIteratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      false,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      createIteratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      true,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      createIteratorFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      false,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9], [9, 10]],
    ],
    [
      createIteratorFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
    ],
  ];
}

function dataProviderForStrings(): Array<unknown> {
  return [
    [
      '',
      1,
      0,
      true,
      [],
    ],
    [
      '',
      1,
      0,
      false,
      [],
    ],
    [
      '',
      2,
      0,
      true,
      [],
    ],
    [
      '',
      2,
      0,
      false,
      [],
    ],
    [
      '',
      2,
      1,
      true,
      [],
    ],
    [
      '',
      2,
      1,
      false,
      [],
    ],
    [
      '1',
      1,
      0,
      true,
      [['1']],
    ],
    [
      '1',
      1,
      0,
      false,
      [['1']],
    ],
    [
      '1',
      1,
      0,
      true,
      [['1']],
    ],
    [
      '1',
      1,
      0,
      false,
      [['1']],
    ],
    [
      '1',
      2,
      0,
      true,
      [['1']],
    ],
    [
      '1',
      2,
      0,
      false,
      [],
    ],
    [
      '1',
      2,
      1,
      true,
      [['1']],
    ],
    [
      '1',
      2,
      1,
      false,
      [],
    ],
    [
      '1',
      3,
      0,
      true,
      [['1']],
    ],
    [
      '1',
      3,
      0,
      false,
      [],
    ],
    [
      '1',
      3,
      1,
      true,
      [['1']],
    ],
    [
      '1',
      3,
      1,
      false,
      [],
    ],
    [
      '1',
      3,
      2,
      true,
      [['1']],
    ],
    [
      '1',
      3,
      2,
      false,
      [],
    ],
    [
      '12',
      1,
      0,
      true,
      [['1'], ['2']],
    ],
    [
      '12',
      1,
      0,
      false,
      [['1'], ['2']],
    ],
    [
      '12',
      2,
      0,
      true,
      [['1', '2']],
    ],
    [
      '12',
      2,
      0,
      false,
      [['1', '2']],
    ],
    [
      '12',
      2,
      1,
      true,
      [['1', '2']],
    ],
    [
      '12',
      2,
      1,
      false,
      [['1', '2']],
    ],
    [
      '12',
      3,
      0,
      true,
      [['1', '2']],
    ],
    [
      '12',
      3,
      0,
      false,
      [],
    ],
    [
      '12',
      3,
      1,
      true,
      [['1', '2']],
    ],
    [
      '12',
      3,
      1,
      false,
      [],
    ],
    [
      '12',
      3,
      2,
      true,
      [['1', '2']],
    ],
    [
      '12',
      3,
      2,
      false,
      [],
    ],
    [
      '123',
      1,
      0,
      true,
      [['1'], ['2'], ['3']],
    ],
    [
      '123',
      1,
      0,
      false,
      [['1'], ['2'], ['3']],
    ],
    [
      '123',
      2,
      0,
      true,
      [['1', '2'], ['3']],
    ],
    [
      '123',
      2,
      0,
      false,
      [['1', '2']],
    ],
    [
      '123',
      2,
      1,
      true,
      [['1', '2'], ['2', '3']],
    ],
    [
      '123',
      2,
      1,
      false,
      [['1', '2'], ['2', '3']],
    ],
    [
      '123',
      3,
      0,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      3,
      0,
      false,
      [['1', '2', '3']],
    ],
    [
      '123',
      3,
      1,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      3,
      1,
      false,
      [['1', '2', '3']],
    ],
    [
      '123',
      3,
      2,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      3,
      2,
      false,
      [['1', '2', '3']],
    ],
    [
      '123',
      4,
      0,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      4,
      0,
      false,
      [],
    ],
    [
      '123',
      4,
      1,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      4,
      1,
      false,
      [],
    ],
    [
      '123',
      4,
      2,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      4,
      2,
      false,
      [],
    ],
    [
      '123',
      4,
      3,
      true,
      [['1', '2', '3']],
    ],
    [
      '123',
      4,
      3,
      false,
      [],
    ],
    [
      '1234',
      2,
      0,
      true,
      [['1', '2'], ['3', '4']],
    ],
    [
      '1234',
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      '1234',
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4']],
    ],
    [
      '1234',
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4']],
    ],
    [
      '1234',
      3,
      0,
      true,
      [['1', '2', '3'], ['4']],
    ],
    [
      '1234',
      3,
      0,
      false,
      [['1', '2', '3']],
    ],
    [
      '1234',
      3,
      1,
      true,
      [['1', '2', '3'], ['3', '4']],
    ],
    [
      '1234',
      3,
      1,
      false,
      [['1', '2', '3']],
    ],
    [
      '1234',
      3,
      2,
      true,
      [['1', '2', '3'], ['2', '3', '4']],
    ],
    [
      '1234',
      3,
      2,
      false,
      [['1', '2', '3'], ['2', '3', '4']],
    ],
    [
      '12345',
      2,
      0,
      true,
      [['1', '2'], ['3', '4'], ['5']],
    ],
    [
      '12345',
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      '12345',
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      '12345',
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      '12345',
      3,
      0,
      true,
      [['1', '2', '3'], ['4', '5']],
    ],
    [
      '12345',
      3,
      0,
      false,
      [['1', '2', '3']],
    ],
    [
      '12345',
      3,
      1,
      true,
      [['1', '2', '3'], ['3', '4', '5']],
    ],
    [
      '12345',
      3,
      1,
      false,
      [['1', '2', '3'], ['3', '4', '5']],
    ],
    [
      '12345',
      3,
      2,
      true,
      [['1', '2', '3'], ['2', '3', '4'], ['3', '4', '5']],
    ],
    [
      '12345',
      3,
      2,
      false,
      [['1', '2', '3'], ['2', '3', '4'], ['3', '4', '5']],
    ],
  ];
}

function dataProviderForSets(): Array<unknown> {
  return [
    [
      new Set([]),
      1,
      0,
      true,
      [],
    ],
    [
      new Set([]),
      1,
      0,
      false,
      [],
    ],
    [
      new Set([]),
      2,
      0,
      true,
      [],
    ],
    [
      new Set([]),
      2,
      0,
      false,
      [],
    ],
    [
      new Set([]),
      2,
      1,
      true,
      [],
    ],
    [
      new Set([]),
      2,
      1,
      false,
      [],
    ],
    [
      new Set([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      new Set([1]),
      1,
      0,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      1,
      0,
      false,
      [[1]],
    ],
    [
      new Set([1]),
      2,
      0,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      2,
      0,
      false,
      [],
    ],
    [
      new Set([1]),
      2,
      1,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      2,
      1,
      false,
      [],
    ],
    [
      new Set([1]),
      3,
      0,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      3,
      0,
      false,
      [],
    ],
    [
      new Set([1]),
      3,
      1,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      3,
      1,
      false,
      [],
    ],
    [
      new Set([1]),
      3,
      2,
      true,
      [[1]],
    ],
    [
      new Set([1]),
      3,
      2,
      false,
      [],
    ],
    [
      new Set([1, 2]),
      1,
      0,
      true,
      [[1], [2]],
    ],
    [
      new Set([1, 2]),
      1,
      0,
      false,
      [[1], [2]],
    ],
    [
      new Set([1, 2]),
      2,
      0,
      true,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      2,
      1,
      true,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      2,
      1,
      false,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      3,
      0,
      true,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      3,
      0,
      false,
      [],
    ],
    [
      new Set([1, 2]),
      3,
      1,
      true,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      3,
      1,
      false,
      [],
    ],
    [
      new Set([1, 2]),
      3,
      2,
      true,
      [[1, 2]],
    ],
    [
      new Set([1, 2]),
      3,
      2,
      false,
      [],
    ],
    [
      new Set([1, 2, 3]),
      1,
      0,
      true,
      [[1], [2], [3]],
    ],
    [
      new Set([1, 2, 3]),
      1,
      0,
      false,
      [[1], [2], [3]],
    ],
    [
      new Set([1, 2, 3]),
      2,
      0,
      true,
      [[1, 2], [3]],
    ],
    [
      new Set([1, 2, 3]),
      2,
      0,
      false,
      [[1, 2]],
    ],
    [
      new Set([1, 2, 3]),
      2,
      1,
      true,
      [[1, 2], [2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      2,
      1,
      false,
      [[1, 2], [2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      3,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      3,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      3,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      3,
      2,
      false,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      4,
      0,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      4,
      0,
      false,
      [],
    ],
    [
      new Set([1, 2, 3]),
      4,
      1,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      4,
      1,
      false,
      [],
    ],
    [
      new Set([1, 2, 3]),
      4,
      2,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      4,
      2,
      false,
      [],
    ],
    [
      new Set([1, 2, 3]),
      4,
      3,
      true,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3]),
      4,
      3,
      false,
      [],
    ],
    [
      new Set([1, 2, 3, 4]),
      2,
      0,
      true,
      [[1, 2], [3, 4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      3,
      0,
      true,
      [[1, 2, 3], [4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3, 4]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      3,
      1,
      false,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3, 4]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      new Set([1, 2, 3, 4]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      2,
      0,
      true,
      [[1, 2], [3, 4], [5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      2,
      0,
      false,
      [[1, 2], [3, 4]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      2,
      1,
      true,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      2,
      1,
      false,
      [[1, 2], [2, 3], [3, 4], [4, 5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      3,
      0,
      true,
      [[1, 2, 3], [4, 5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      3,
      0,
      false,
      [[1, 2, 3]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      3,
      2,
      true,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      new Set([1, 2, 3, 4, 5]),
      3,
      2,
      false,
      [[1, 2, 3], [2, 3, 4], [3, 4, 5]],
    ],
    [
      new Set([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      true,
      [[1.1, 2.2], [3.3, 4.4], [5.5]],
    ],
    [
      new Set([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      false,
      [[1.1, 2.2], [3.3, 4.4]],
    ],
    [
      new Set([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      true,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      new Set([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      false,
      [[1.1, 2.2], [2.2, 3.3], [3.3, 4.4], [4.4, 5.5]],
    ],
    [
      new Set(['1', '2', '3', '4', '5']),
      2,
      0,
      true,
      [['1', '2'], ['3', '4'], ['5']],
    ],
    [
      new Set(['1', '2', '3', '4', '5']),
      2,
      0,
      false,
      [['1', '2'], ['3', '4']],
    ],
    [
      new Set(['1', '2', '3', '4', '5']),
      2,
      1,
      true,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      new Set(['1', '2', '3', '4', '5']),
      2,
      1,
      false,
      [['1', '2'], ['2', '3'], ['3', '4'], ['4', '5']],
    ],
    [
      new Set([[1], [2], [3], [4], [5]]),
      2,
      0,
      true,
      [[[1], [2]], [[3], [4]], [[5]]],
    ],
    [
      new Set([[1], [2], [3], [4], [5]]),
      2,
      0,
      false,
      [[[1], [2]], [[3], [4]]],
    ],
    [
      new Set([[1], [2], [3], [4], [5]]),
      2,
      1,
      true,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      new Set([[1], [2], [3], [4], [5]]),
      2,
      1,
      false,
      [[[1], [2]], [[2], [3]], [[3], [4]], [[4], [5]]],
    ],
    [
      new Set([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      true,
      [[1, 2.2, '3'], [[4], true, null], ['test data']],
    ],
    [
      new Set([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      false,
      [[1, 2.2, '3'], [[4], true, null]],
    ],
    [
      new Set([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      true,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      new Set([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      false,
      [[1, 2.2, '3'], ['3', [4], true], [true, null, 'test data']],
    ],
    [
      new Set([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      true,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      new Set([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      false,
      [[1, 2.2, '3'], [2.2, '3', [4]], ['3', [4], true], [[4], true, null], [true, null, 'test data']],
    ],
    [
      new Set(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      true,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      new Set(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      false,
      [['Ross', 'Rachel'], ['Chandler', 'Monica'], ['Joey', 'Phoebe']],
    ],
    [
      new Set(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      true,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      new Set(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      false,
      [['Ross', 'Rachel'], ['Rachel', 'Chandler'], ['Chandler', 'Monica'], ['Monica', 'Joey'], ['Joey', 'Phoebe']],
    ],
    [
      new Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      true,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9], [9, 10]],
    ],
    [
      new Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      false,
      [[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]],
    ],
  ];
}

function dataProviderForMaps(): Array<unknown> {
  return [
    [
      createMapFixture([]),
      1,
      0,
      true,
      [],
    ],
    [
      createMapFixture([]),
      1,
      0,
      false,
      [],
    ],
    [
      createMapFixture([]),
      2,
      0,
      true,
      [],
    ],
    [
      createMapFixture([]),
      2,
      0,
      false,
      [],
    ],
    [
      createMapFixture([]),
      2,
      1,
      true,
      [],
    ],
    [
      createMapFixture([]),
      2,
      1,
      false,
      [],
    ],
    [
      createMapFixture([1]),
      1,
      0,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      1,
      0,
      false,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      1,
      0,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      1,
      0,
      false,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      2,
      0,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      2,
      0,
      false,
      [],
    ],
    [
      createMapFixture([1]),
      2,
      1,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      2,
      1,
      false,
      [],
    ],
    [
      createMapFixture([1]),
      3,
      0,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      3,
      0,
      false,
      [],
    ],
    [
      createMapFixture([1]),
      3,
      1,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      3,
      1,
      false,
      [],
    ],
    [
      createMapFixture([1]),
      3,
      2,
      true,
      [[[0, 1]]],
    ],
    [
      createMapFixture([1]),
      3,
      2,
      false,
      [],
    ],
    [
      createMapFixture([1, 2]),
      1,
      0,
      true,
      [[[0, 1]], [[1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      1,
      0,
      false,
      [[[0, 1]], [[1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      2,
      0,
      true,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      2,
      0,
      false,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      2,
      1,
      true,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      2,
      1,
      false,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      3,
      0,
      true,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      3,
      0,
      false,
      [],
    ],
    [
      createMapFixture([1, 2]),
      3,
      1,
      true,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      3,
      1,
      false,
      [],
    ],
    [
      createMapFixture([1, 2]),
      3,
      2,
      true,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2]),
      3,
      2,
      false,
      [],
    ],
    [
      createMapFixture([1, 2, 3]),
      1,
      0,
      true,
      [[[0, 1]], [[1, 2]], [[2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      1,
      0,
      false,
      [[[0, 1]], [[1, 2]], [[2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      2,
      0,
      true,
      [[[0, 1], [1, 2]], [[2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      2,
      0,
      false,
      [[[0, 1], [1, 2]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      2,
      1,
      true,
      [[[0, 1], [1, 2]], [[1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      2,
      1,
      false,
      [[[0, 1], [1, 2]], [[1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      3,
      0,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      3,
      0,
      false,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      3,
      1,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      3,
      1,
      false,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      3,
      2,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      3,
      2,
      false,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      0,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      0,
      false,
      [],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      1,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      1,
      false,
      [],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      2,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      2,
      false,
      [],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      3,
      true,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3]),
      4,
      3,
      false,
      [],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      2,
      0,
      true,
      [[[0, 1], [1, 2]], [[2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      2,
      0,
      false,
      [[[0, 1], [1, 2]], [[2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      2,
      1,
      true,
      [[[0, 1], [1, 2]], [[1, 2], [2, 3]], [[2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      2,
      1,
      false,
      [[[0, 1], [1, 2]], [[1, 2], [2, 3]], [[2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      3,
      0,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      3,
      0,
      false,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      3,
      1,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      3,
      1,
      false,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      3,
      2,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[1, 2], [2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4]),
      3,
      2,
      false,
      [[[0, 1], [1, 2], [2, 3]], [[1, 2], [2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      2,
      0,
      true,
      [[[0, 1], [1, 2]], [[2, 3], [3, 4]], [[4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      2,
      0,
      false,
      [[[0, 1], [1, 2]], [[2, 3], [3, 4]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      2,
      1,
      true,
      [[[0, 1], [1, 2]], [[1, 2], [2, 3]], [[2, 3], [3, 4]], [[3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      2,
      1,
      false,
      [[[0, 1], [1, 2]], [[1, 2], [2, 3]], [[2, 3], [3, 4]], [[3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      3,
      0,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      3,
      0,
      false,
      [[[0, 1], [1, 2], [2, 3]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      3,
      1,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[2, 3], [3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      3,
      1,
      false,
      [[[0, 1], [1, 2], [2, 3]], [[2, 3], [3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      3,
      2,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[1, 2], [2, 3], [3, 4]], [[2, 3], [3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5]),
      3,
      2,
      false,
      [[[0, 1], [1, 2], [2, 3]], [[1, 2], [2, 3], [3, 4]], [[2, 3], [3, 4], [4, 5]]],
    ],
    [
      createMapFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      true,
      [[[0, 1.1], [1, 2.2]], [[2, 3.3], [3, 4.4]], [[4, 5.5]]],
    ],
    [
      createMapFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      0,
      false,
      [[[0, 1.1], [1, 2.2]], [[2, 3.3], [3, 4.4]]],
    ],
    [
      createMapFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      true,
      [
        [[0, 1.1], [1, 2.2]],
        [[1, 2.2], [2, 3.3]],
        [[2, 3.3], [3, 4.4]],
        [[3, 4.4], [4, 5.5]],
      ],
    ],
    [
      createMapFixture([1.1, 2.2, 3.3, 4.4, 5.5]),
      2,
      1,
      false,
      [
        [[0, 1.1], [1, 2.2]],
        [[1, 2.2], [2, 3.3]],
        [[2, 3.3], [3, 4.4]],
        [[3, 4.4], [4, 5.5]],
      ],
    ],
    [
      createMapFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      true,
      [[[0, '1'], [1, '2']], [[2, '3'], [3, '4']], [[4, '5']]],
    ],
    [
      createMapFixture(['1', '2', '3', '4', '5']),
      2,
      0,
      false,
      [[[0, '1'], [1, '2']], [[2, '3'], [3, '4']]],
    ],
    [
      createMapFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      true,
      [[[0, '1'], [1, '2']], [[1, '2'], [2, '3']], [[2, '3'], [3, '4']], [[3, '4'], [4, '5']]],
    ],
    [
      createMapFixture(['1', '2', '3', '4', '5']),
      2,
      1,
      false,
      [[[0, '1'], [1, '2']], [[1, '2'], [2, '3']], [[2, '3'], [3, '4']], [[3, '4'], [4, '5']]],
    ],
    [
      createMapFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      true,
      [[[0, [1]], [1, [2]]], [[2, [3]], [3, [4]]], [[4, [5]]]],
    ],
    [
      createMapFixture([[1], [2], [3], [4], [5]]),
      2,
      0,
      false,
      [[[0, [1]], [1, [2]]], [[2, [3]], [3, [4]]]],
    ],
    [
      createMapFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      true,
      [[[0, [1]], [1, [2]]], [[1, [2]], [2, [3]]], [[2, [3]], [3, [4]]], [[3, [4]], [4, [5]]]],
    ],
    [
      createMapFixture([[1], [2], [3], [4], [5]]),
      2,
      1,
      false,
      [[[0, [1]], [1, [2]]], [[1, [2]], [2, [3]]], [[2, [3]], [3, [4]]], [[3, [4]], [4, [5]]]],
    ],
    [
      createMapFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      true,
      [[[0, 1], [1, 2.2], [2, '3']], [[3, [4]], [4, true], [5, null]], [[6, 'test data']]],
    ],
    [
      createMapFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      0,
      false,
      [[[0, 1], [1, 2.2], [2, '3']], [[3, [4]], [4, true], [5, null]]],
    ],
    [
      createMapFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      true,
      [[[0, 1], [1, 2.2], [2, '3']], [[2, '3'], [3, [4]], [4, true]], [[4, true], [5, null], [6, 'test data']]],
    ],
    [
      createMapFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      1,
      false,
      [[[0, 1], [1, 2.2], [2, '3']], [[2, '3'], [3, [4]], [4, true]], [[4, true], [5, null], [6, 'test data']]],
    ],
    [
      createMapFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      true,
      [
        [[0, 1], [1, 2.2], [2, '3']],
        [[1, 2.2], [2, '3'], [3, [4]]],
        [[2, '3'], [3, [4]], [4, true]],
        [[3, [4]], [4, true], [5, null]],
        [[4, true], [5, null], [6, 'test data']],
      ],
    ],
    [
      createMapFixture([1, 2.2, '3', [4], true, null, 'test data']),
      3,
      2,
      false,
      [
        [[0, 1], [1, 2.2], [2, '3']],
        [[1, 2.2], [2, '3'], [3, [4]]],
        [[2, '3'], [3, [4]], [4, true]],
        [[3, [4]], [4, true], [5, null]],
        [[4, true], [5, null], [6, 'test data']],
      ],
    ],
    [
      createMapFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      true,
      [[[0, 'Ross'], [1, 'Rachel']], [[2, 'Chandler'], [3, 'Monica']], [[4, 'Joey'], [5, 'Phoebe']]],
    ],
    [
      createMapFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      0,
      false,
      [[[0, 'Ross'], [1, 'Rachel']], [[2, 'Chandler'], [3, 'Monica']], [[4, 'Joey'], [5, 'Phoebe']]],
    ],
    [
      createMapFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      true,
      [
        [[0, 'Ross'], [1, 'Rachel']],
        [[1, 'Rachel'], [2, 'Chandler']],
        [[2, 'Chandler'], [3, 'Monica']],
        [[3, 'Monica'], [4, 'Joey']],
        [[4, 'Joey'], [5, 'Phoebe']]],
    ],
    [
      createMapFixture(['Ross', 'Rachel', 'Chandler', 'Monica', 'Joey', 'Phoebe']),
      2,
      1,
      false,
      [
        [[0, 'Ross'], [1, 'Rachel']],
        [[1, 'Rachel'], [2, 'Chandler']],
        [[2, 'Chandler'], [3, 'Monica']],
        [[3, 'Monica'], [4, 'Joey']],
        [[4, 'Joey'], [5, 'Phoebe']]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      true,
      [[[0, 1], [1, 2], [2, 3]], [[2, 3], [3, 4], [4, 5]], [[4, 5], [5, 6], [6, 7]], [[6, 7], [7, 8], [8, 9]], [[8, 9], [9, 10]]],
    ],
    [
      createMapFixture([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      3,
      1,
      false,
      [[[0, 1], [1, 2], [2, 3]], [[2, 3], [3, 4], [4, 5]], [[4, 5], [5, 6], [6, 7]], [[6, 7], [7, 8], [8, 9]]],
    ],
  ];
}

function dataProviderForError(): Array<unknown> {
  return [
    [
      [],
      0,
      0,
      true,
    ],
    [
      [],
      -1,
      0,
      false,
    ],
    [
      [1, 2, 3],
      -2,
      0,
      true,
    ],
    [
      [1, 2, 3],
      1,
      2,
      false,
    ],
    [
      [1, 2, 3],
      2,
      3,
      true,
    ],
    [
      [1, 2, 3],
      3,
      5,
      false,
    ],
  ];
}
